baseURL = 'https://acurry.github.io/'
languageCode = 'en-us'
title = 'acurry.github.io'
theme = 'lekh'

[params]
Name = "andrew d curry"
About = "I'm a full-stack web developer in the DMV area, currently working at Dragos as a Staff Software Engineer since Jan 2018."
Email = ""
Resume = "" # Add the filename with file extension.
PostLimit = 4 # Sets the number of posts to display on the front page
GoatCounterCode = ""

[[params.profiles]]
name = "GitHub"
url = "https://github.com/acurry"

[[params.profiles]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/andrew-curry-bb607711/"